# brew install pre-commit
# pre-commit install
#
#
#
# Note: If any of the version here differ from what we have in requirements-dev.txt
# feel free to update them here and make a PR.

default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      # - id: trailing-whitespace
      # - id: sort-simple-yaml
      # - id: check-docstring-first
      # - id: pretty-format-json

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-quotes==2.1.1"]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--safe, --quiet]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --python-version=3.9]
        additional_dependencies:
          [
            "attrs==21.4.0",
            "pyjwt==2.0.1",
            "tokenize-rt==3.2.0",
            "types-Deprecated==1.2.3",
            "types-PyYAML==6.0.1",
            "types-bleach==4.1.1",
            "types-boto==2.49.2",
            "types-certifi==2021.10.8.0",
            "types-cryptography==3.3.9",
            "types-enum34==1.1.1",
            "types-freezegun==1.1.3",
            "types-ipaddress==1.0.1",
            "types-orjson==3.6.1",
            "types-pyOpenSSL==21.0.1",
            "types-python-dateutil==2.8.3",
            "types-pytz==2021.3.3",
            "types-redis==4.0.5",
            "types-requests==2.26.2",
            "types-six==1.16.3",
            "types-toml==0.10.1",
            "types-tzlocal==3.0.0",
          ]

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
      - id: pylint
        # Disable F0401 so we don't need to copy all the packages in requirements.txt
        args: [--rcfile=pylintrc, -j 0, --disable=F0401]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.1
    hooks:
      - id: sqlfluff-lint
        args:
          [
            "--dialect",
            "postgres",
            "--config",
            "eltops/dbt/zenput_elt/.sqlfluff",
          ]

  # commented out because it might cause too much noise

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #       - id: codespell
  #         # nd is ignored because it's part of a private key string and somehow i don't
  #         # know how to ignore just that line with codespel.
  #         # PS: I know we should not have keys in our codebase
  #         # exceptions
  #         #   - nin = valid mongo query string
  #         #   - nd = some part of a key that codespell thinks shoud be a word.
  #         args: ["-L", "nd,criterias,doubleclick,nin"]
